pipeline {
    agent any
    environment{
        user = "Bharath"
        secret = credentials('ID00')
    }

    stages{
        stage("build"){
            steps{
                echo 'building app'
                echo "User is : ${user}"
            }      
        }
        stage("test"){
            steps{
               input("Continue?") 
            }

        }
        stage("deploy"){
            steps{
             echo "Password is :${secret}"   
            }
        }

    }
   post{

       always {
           echo"This is executed everything"
       }
		failure{    
		    echo "Failed"
		}
		success{
		    echo "Success"
		}

   }
 
   

}