def gv

pipeline {
    agent any
    environment{
        user = "Bharath"
        secret = credentials('ID00')
    }
	parameters{
	    choice(name: 'VERSION',choices:['1.1.0','1.2.0','1.3.0'], description:'')
	    booleanParam(name: 'executeTests', defaultValue:true, description:'')
	}

    stages{
    
    	stage("init"){
    	    steps{
    	        script{
    	            gv = load "PipelineDemo/script.groovy"
    	        }

    	    }

    	}

        stage("build"){
            steps{
                script{
                    gv.buildApp()
                }

            }      
        }
        stage("test"){
        when{
            expression{
                params.executeTests == true
            }

        }
            steps{
              script{
                  
                  gv.TestingApp()
              }

            }

        }
        stage("deploy"){
            steps{
                script{
                    gv.DeployingApp()
                }

            }
        }
        stage("multiple"){
            parallel {
                stage("Unit test"){
                steps{
                     script{
    				gv.Unit()
				}
  
                }


                    
                }
			stage('Integration test'){
			  steps{
                   script{
                      gv.Integration()
                   }

                }
			    
			}

            }
            
        }


    }
   post{

       always {
           echo"This is executed everytime"
       }
		failure{    
		    echo "Failed"
		}
		success{
		    echo "Success"
		}
   }
}